[project]
name = "tmux-path-store"
version = "1.0.0"
description = "Uses the Tmux window name as an index into a list of stored directory paths and files."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.ruff]
line-length = 110
target-version = "py314"
